### ISSUE TITLE
reload

### ISSUE THREAD

**Issue by adityaabothra** [dphi-official/Deep_Learning_Bootcamp#6]
I have been reloading it for 20-30 times it still showing some problem.

**Comment by chanukyapatnaik** [comment]
@adityaabothra maybe it could be a browser/machine issue. Could you please download the repo instead? that would be seamless

**Comment by adityaabothra** [comment]
Hi sir,

Due to getting tested positive for covid and bad health I couldn't complete
the 2nd assignment on time.
It all happened in past week and u couldn't try.

Can I submit it by tomorrow as i have now recovered somewhat to complete my
task.

Regards
Aditya
